apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pycrest-uploads-pvc
  namespace: pycrest
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi