apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: frontend-deployment 
  namespace: pc-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: wallet 
  template:
    metadata:
      labels:
        app: wallet 
    spec:
      affinity:
        podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: wallet 
                  topologyKey: "kubernetes.io/hostname"
      containers:
        - name: frontend-wallet-cont 
          image: chillmadiguys/wallet-service:v1.1.1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/uploads 
      volumes:
        - name: loan-volume
          persistentVolumeClaim:
            claimName: loan-pvc
        
          envFrom:
            - configMapRef:
                name: wallet-configmap
            - secretRef:
                name: wallet-secret 
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
 
         
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 20
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          #   failureThreshold: 3
              