apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: pycrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      serviceAccountName: admin-service-sa
      containers:
        - name: admin-service
          image: chillmadiguys/admin-service:v1.1.0
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pycrest-global-config
            - secretRef:
                name: pycrest-global-secret

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pycrest-uploads-pvc