apiVersion: v1
kind: Secret 
metadata:
  name: mongo-secret 
  namespace: pc-data 
  type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: pycrest
  MONGO_INITDB_ROOT_PASSWORD: pycrest123
  MONGO_INITDB_DATABASE: pycrest