apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: pc-data 
spec:
  replicas: 3
  serviceName: mongodb 
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mongodb
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          
          resources:   # resource can be changed according to the useage
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret #Mapped using secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD

            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_DATABASE

          volumeMounts:
            - name: mongo-data 
              mountPath: /data/db 

  volumeClaimTemplates:
    - metadata:
        name: mongo-data 
      spec:
        accessModes: 
          - "ReadWriteOnce"
        storageClassName: nfs-csi 
        resources:
          requests:
            storage: 10Gi #requested storage

