apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: verification-service-hpa
  namespace: pycrest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: verification-service
  minReplicas: 1
  maxReplicas: 3