apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: loan-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}