apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
  namespace: pc-app
  labels:
    app: verification-service
    {{- include "paycrest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.verificationService.replicas }}
  selector:
    matchLabels:
      app: verification-service
  {{- include "paycrest.rollingUpdate" . | nindent 2 }}
  template:
    metadata:
      labels:
        app: verification-service
    spec:
      {{- include "paycrest.antiAffinity" "verification-service" | nindent 6 }}
      containers:
        - name: verification-service-cont
          image: {{ .Values.verificationService.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.verificationService.resources | nindent 12 }}
          envFrom:
            {{- include "paycrest.appEnvFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "paycrest.uploadVolumeMount" . | nindent 12 }}
          {{- include "paycrest.appProbes" . | nindent 10 }}
      volumes:
        {{- include "paycrest.uploadVolume" . | nindent 8 }}
