apiVersion: v1
kind: Secret
metadata:
  name: pc-secret-api
  namespace: pc-edge
  labels:
    {{- include "paycrest.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.apiGateway.jwtSecret | quote }}
  JWT_ALGORITHM: {{ .Values.apiGateway.jwtAlgorithm | quote }}
  PORT: {{ .Values.apiGateway.port | quote }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.apiGateway.internalServiceToken | quote }}
  AUTH_SERVICE_URL: "http://auth-service.pc-app.svc.cluster.local:8000"
  LOAN_SERVICE_URL: "http://loan-service.pc-app.svc.cluster.local:8000"
  EMI_SERVICE_URL: "http://emi-service.pc-app.svc.cluster.local:8000"
  WALLET_SERVICE_URL: "http://wallet-service.pc-app.svc.cluster.local:8000"
  PAYMENT_SERVICE_URL: "http://payment-service.pc-app.svc.cluster.local:8000"
  VERIFICATION_SERVICE_URL: "http://verification-service.pc-app.svc.cluster.local:8000"
  ADMIN_SERVICE_URL: "http://admin-service.pc-app.svc.cluster.local:8000"
  MANAGER_SERVICE_URL: "http://manager-service.pc-app.svc.cluster.local:8000"
  AUDIT_SERVICE_URL: "http://admin-service.pc-app.svc.cluster.local:8000"
