apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: pc-data
  labels:
    {{- include "paycrest.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.credentials.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.credentials.password | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.credentials.database | quote }}