apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-isolation
  namespace: pc-app
spec:
  podSelector: {} 
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from: 
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: pc-edge
      ports:
      - protocol: TCP
        port: 8000 
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: pc-data
      ports:
      - protocol: TCP
        port: 27017

    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53