apiGateway:
  image: "chillmadiguys/api-gateway:v1.1.3"
  port: "3000"
  jwtSecret: "pycrest_jwt_secret_devops_2024"
  jwtAlgorithm: "HS256"
  internalServiceToken: "e9ccbcbfd93e305d56e67a751664bd4b79ed32b23a896cc71958b98008f0fbcb"
  hpa:
    minReplicas: 2
    maxReplicas: 4
    cpuUtilization: 70
    memoryUtilization: 80
  resources:
    requests:
      cpu: "100m"
      memory: "96Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"