# Deployment file for admin service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: pc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  strategy: # Strategy for deployment
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # How many pods can go down
      maxSurge: 1 # How many pods can create
  template:
    metadata: 
      labels:
        app: admin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: admin
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: admin-cont
          image: chillmadiguys/admin-service:v1.1.1
          ports:
            - containerPort: 8000
          resources: # Used resources to avoid utilizing full resources of cluster
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          envFrom: 
            - secretRef:
                name: pc-secrets-app
            - configMapRef:
                name: pc-config
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: admin-pvc

                

    