apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-pvc
  namespace: pc-app
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 