apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: pc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: auth-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: auth-service
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: auth-service
          image: chillmadiguys/auth-service:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          envFrom: 
            - secretRef:
                name: pc-secrets-global
            - configMapRef:
                name: pc-config-global
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pc-upload-pvc

                

    