apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: admin-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            - secretRef:
                name: {{ .Values.secretName }}

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}