apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deploy
  namespace: pc-app
spec:
  replicas:
  selector:
    matchLabels:
      app: loan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan-container
          image: chillmadiguys/loan-service:v1.1.1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: loan-configmap
            - secretRef:
                name: loan-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMount:
            - name: loan-volume
              mountPath: /data/db
      volume:
        - name: loan-volume
          persistentVolumeClaim:
            claimName: loan-pvc
          