apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deploy
  namespace: pc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: loan
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - loan
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: loan-container
          image: chillmadiguys/loan-service:v1.1.1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: loan-configmap
            - secretRef:
                name: loan-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMount:
            - name: loan-volume
              mountPath: /app/uploads
      volume:
        - name: loan-volume
          persistentVolumeClaim:
            claimName: loan-pvc
          