
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: pc-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: pycrest
  MONGO_INITDB_ROOT_PASSWORD: pycrest123
  MONGO_INITDB_DATABASE: pycrest
  password: pycrest
 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: pc-app
spec:
  replicas: 3
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mongodb
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
         
          resources:   # resource can be changed according to the useage
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
 
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret #Mapped using secrets
                  key: MONGO_INITDB_ROOT_USERNAME
           
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
 
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_DATABASE
 
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
 
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - "ReadWriteMany"
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 10Gi #requested storage

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: pc-app
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017