apiVersion: apps/v1
kind: Deployment
metadata:
  name: emi-service
  namespace: pycrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emi-service
  template:
    metadata:
      labels:
        app: emi-service
    spec:
      serviceAccountName: emi-service-sa
      containers:
        - name: emi-service
          image: chillmadiguys/emi-service:v1.1.0
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pycrest-global-config
            - secretRef:
                name: pycrest-global-secret

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi