apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pc-app1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: verification
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: frontend-verification-cont
          image: chillmadiguys/verification-service:v1.1.1
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

        
          envFrom:
            - configMapRef:
                name: verification-configmap
            - secretRef:
                name: verification-secret

          volumeMounts:
            - name: verification-volume
              mountPath: /app/uploads

      volumes:
        - name: verification-volume
          persistentVolumeClaim:
            claimName: verification-pvc