apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verification-pvc
  namespace: pc-app1
spec:
  storageClassName: nfs-csi12
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"