apiVersion: v1 
kind: Secret 
metadata:
  name: verification-secret
  namespace: pc-app1
type: Opaque 
stringData:
  MONGODB_URI: "mongodb://pycrest:pycrest123@mongodb:27017/pycrest?authSource=admin"
  MONGODB_DB: "pycrest"
  JWT_SECRET: "pycrest_jwt_secret_devops_2024"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"
  INTERNAL_SERVICE_TOKEN: "e9ccbcbfd93e305d56e67a751664bd4b79ed32b23a896cc71958b98008f0fbcb"