apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: wallet-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}