apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: pc-app
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 