apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service 
  namespace: pc-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: wallet-service
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: wallet-service-cont
          image: chillmadiguys/wallet-service:v1.1.1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: pc-config-global
            - secretRef:
                name: pc-secrets-global
          volumeMounts:
            - name: wallet-volume
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: wallet-volume
          persistentVolumeClaim:
            claimName: pc-upload-pvc