apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: pc-app
  labels:
    app: wallet-service
    {{- include "paycrest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.walletService.replicas }}
  selector:
    matchLabels:
      app: wallet-service
  {{- include "paycrest.rollingUpdate" . | nindent 2 }}
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      {{- include "paycrest.antiAffinity" "wallet-service" | nindent 6 }}
      containers:
        - name: wallet-service-cont
          image: {{ .Values.walletService.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.walletService.resources | nindent 12 }}
          envFrom:
            {{- include "paycrest.appEnvFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "paycrest.uploadVolumeMount" . | nindent 12 }}
          {{- include "paycrest.appProbes" . | nindent 10 }}
      volumes:
        {{- include "paycrest.uploadVolume" . | nindent 8 }}
