apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
  namespace: pycrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verification-service
  template:
    metadata:
      labels:
        app: verification-service
    spec:
      serviceAccountName: verification-service-sa

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: verification-service
                topologyKey: kubernetes.io/hostname

      containers:
        - name: verification-service
          image: chillmadiguys/verification-service:v1.1.0
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pycrest-global-config
            - secretRef:
                name: pycrest-global-secret

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pycrest-uploads-pvc