apiGateway:
  image: "chillmadiguys/api-gateway:v1.1.5"
  hpa:
    minReplicas: 2
    maxReplicas: 4
    cpuUtilization: 70
    memoryUtilization: 80
  resources:
    requests:
      cpu: "100m"
      memory: "96Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"