apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: loan-service
  namespace: pc-app
  labels:
    app: loan-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: loan-service
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: loan-container
          image: {{ .Values.loanService.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.loanService.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: pc-config-global
            - secretRef:
                name: pc-secrets-global
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pc-upload-pvc
  strategy:
    blueGreen:
      activeService: loan-service
      previewService: loan-service-preview
      autoPromotionEnabled: false