apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-service
  namespace: pc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-service
  template:
    metadata:
      labels:
        app: manager-service
    spec:
      containers:
        - name: manager-service
          image: chillmadiguys/manager-service:v1.1.0
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pycrest-global-config
            - secretRef:
                name: pycrest-global-secret

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pycrest-uploads-pvc
