apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manager-pvc
  namespace: pc-app
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"