apiVersion: v1
kind: Secret
metadata:
  name: pc-secrets-global
  namespace: pc-app
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.appSecrets.mongodbUri | quote }}
  MONGODB_DB: {{ .Values.appSecrets.mongodbDb | quote }}
  JWT_SECRET: {{ .Values.appSecrets.jwtSecret | quote }}
  JWT_SECRET_KEY: {{ .Values.appSecrets.jwtSecret | quote }}
  JWT_ALGORITHM: {{ .Values.appSecrets.jwtAlgorithm | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.appSecrets.jwtExpireMinutes | quote }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.appSecrets.internalServiceToken | quote }}
  AUTH_SERVICE_URL: "http://auth-service.pc-app.svc.cluster.local:8000"
  LOAN_SERVICE_URL: "http://loan-service.pc-app.svc.cluster.local:8000"
  EMI_SERVICE_URL: "http://emi-service.pc-app.svc.cluster.local:8000"
  WALLET_SERVICE_URL: "http://wallet-service.pc-app.svc.cluster.local:8000"
  PAYMENT_SERVICE_URL: "http://payment-service.pc-app.svc.cluster.local:8000"
  VERIFICATION_SERVICE_URL: "http://verification-service.pc-app.svc.cluster.local:8000"
  ADMIN_SERVICE_URL: "http://admin-service.pc-app.svc.cluster.local:8000"
  MANAGER_SERVICE_URL: "http://manager-service.pc-app.svc.cluster.local:8000"
  AUDIT_SERVICE_URL: "http://admin-service.pc-app.svc.cluster.local:8000"