apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-service
  namespace: pc-app
  labels:
    app: manager-service
    {{- include "paycrest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.managerService.replicas }}
  selector:
    matchLabels:
      app: manager-service
  {{- include "paycrest.rollingUpdate" . | nindent 2 }}
  template:
    metadata:
      labels:
        app: manager-service
    spec:
      containers:
        - name: manager-service
          image: {{ .Values.managerService.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.managerService.resources | nindent 12 }}
          envFrom:
            {{- include "paycrest.appEnvFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "paycrest.uploadVolumeMount" . | nindent 12 }}
          {{- include "paycrest.appProbes" . | nindent 10 }}
      volumes:
        {{- include "paycrest.uploadVolume" . | nindent 8 }}
