name: API Gateway CI/CD

on:
  pull_request:
    branches: [test, master]
    paths: ['api-gateway/**']
  push:
    branches: [test]
    paths: ['api-gateway/**']

jobs:
  ci:
    uses: ./.github/workflows/_ci-node.yml
    with:
      service: api-gateway
      image: chillmadiguys/api-gateway
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GATEWAY }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      DEVELOPMENT_TEAM_EMAIL: ${{ secrets.DEVELOPMENT_TEAM_EMAIL }}