name: Loan Service CI/CD

on:
  pull_request:
    branches: [test, master]
    paths: ['loan-service/**']
  push:
    branches: [test]
    paths: ['loan-service/**']

jobs:
  ci:
    uses: ./.github/workflows/_ci-python.yml
    with:
      service: loan-service
      image: chillmadiguys/loan-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_LOAN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      DEVELOPMENT_TEAM_EMAIL: ${{ secrets.DEVELOPMENT_TEAM_EMAIL }}